### ISSUE TITLE
unable to run eatpdb

### ISSUE THREAD

**Issue by ambiennt** [codehz/EatPdb#2]
![image](https://user-images.githubusercontent.com/63216972/148198913-3f955293-87d3-458c-a237-a48975af295d.png)

**Comment by ambiennt** [comment]
I extracted the contents of the latest release to a folder, I put my bedrock_server.pdb and bedrock_server.exe (BDS) files in that same directory. I added a `config.yaml` file with the contents on the readme but replaced the in and out.

config.yaml: 
```
in: bedrock_server.exe
out: bedrock_server_mod.exe
filter: !blacklist
  - prefix: "_"
  - prefix: "?__"
  - prefix: "??_"
  - prefix: "??@"
  - prefix: "?$TSS"
  - regex: "std@@[QU]"
  - name: "atexit"
  ```
  
 I opened command prompt in administrator mode and ran `eatpdb exec config.yaml`, and thats the error I get.

**Comment by codehz** [comment]
you need provide filterdb in config (just a output filename)
```yaml
in: bedrock_server.exe
out: bedrock_server_mod.exe
filterdb: extra.db
filter: !blacklist
  - prefix: "_"
  - prefix: "?__"
  - prefix: "??_"
  - prefix: "??@"
  - prefix: "?$TSS"
  - regex: "std@@[QU]"
  - name: "atexit"
```
